server:
  port: 8082

spring:
  application:
    name: movie-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost
    